import random

DEPARTURE_TEXTS = [
    "The roar of the bazaar lingers as your ship rises from the landing pad. Vendors shout final offers, star-charts flap in the wind, and a haggling droid curses in binary as you slip away. The sun hits the durasteel rooftops at a harsh angle, turning the whole port into a patchwork of glowing steel. With a final hiss of vapor, your thrusters kick, lifting you above the noise, the smell of spice-dust, and the teeming crowds. Space stretches ahead — quiet, cold, and nothing like the chaos below.",
    "You bank left, gliding past the rusted communications spire where underpaid controllers wave traffic through with more hope than precision. Ships of every legal status flash their running lights as they weave between freight haulers and smugglers pretending to be freight haulers. The whole port looks like a metal anthill from up here — bustling, bright, and just a little lawless. By the time your nav-computer locks onto the next sector, the planet’s haze has already swallowed the port behind you.",
    "Your engines punch through the thick amber smog clinging to the port like a second atmosphere. Below, the fuel depots flicker with blue flame and the cantina district buzzes with neon signs advertising things no sane pilot would try. You shake off the grit, literally — the hull rattles from blown sand and stray refuse — and the port dissolves into a grid of trembling lights. Ahead lies open void and whatever waits for you in the next sector.",
    "As you lift off, you can feel it — hundreds of eyes tracking your ship. Dock workers, scavengers, bounty hunters, and drifters all look up for just a heartbeat, wondering whether you’ll return rich, ruined, or not at all. You clear the docking rings, each one humming with magnetic coils that tug at your ship’s plating. When the last ring falls away, the port becomes nothing more than a scar of bright metal on the planet’s skin. Space welcomes you with indifferent silence.",
    "Traffic control cracks over your comm with a bored warning you promptly ignore. Four ships cut across your path, engines whining like dying beasts. A bulk carrier belches coolant into the sky as someone swears at it in four languages. You thrust past the chaos, leaving the clang of cargo cranes and the electro-jazz thumping from a rooftop bar behind. Then — just like walking through a door — the noise dies and stars bloom across your canopy.",
    "Your ship rises over a patchwork hellscape of scavenger huts, jury-rigged refueling stations, and the skeletal remains of older vessels. Sparks fly as welders tear another derelict apart. Kids chase each other between towering mounds of scrap. A mechanical beast — half loader, half garbage compactor — roars to life beneath you. Once you clear the outer ring, the scrapyard becomes a swirl of metallic color, and you’re free of the gravitational pull of that chaotic world.",
    "You pass over the glow of night markets and cantinas still throbbing with music. Shadows dance between buildings as smugglers deal spice, starfarers bluff through card games, and droids argue with barkeeps. The whole district hums like a neon beehive — vibrant, loud, and dangerous if you look at anyone too long. You angle up, engines spooling hot, and the lights dissolve into a smear of electric color as you break for orbit.",
    "Leaving the port means threading your way through the drifting junk cloud — everything from broken panels to the occasional unreported corpse. Thrusters flare, shields flicker, and warning lights ping as debris skitters off your hull. Below, the port’s floodlights carve sharp shadows across the wasteland of cargo pallets and fuel pools. Then, with a final jolt, you break free of the cloud and the void opens wide before you.",
    "A pair of bored port security craft track you for exactly three seconds before returning to their card game. On the docks below, a brawl breaks out near a spice stall while a preacher shouts doomsday prophecies at passing miners. Your ship climbs steadily, the din fading into a faint rumble. Once you breach the upper atmosphere, the port becomes a bright scar on the horizon — small, loud, and full of trouble you’re glad to leave behind.",
    "Heat vents belch steam upward, fogging the lower viewing ports. You rise past the undercity’s rusted walkways and patched-together apartments stacked like mismatched bricks. A shuttle screams by on emergency burn, chased by two smaller ships with weapons charged. Typical day. You punch your thrusters, roll starboard, and the entire mess of humanity, droids, thieves, traders, and saints collapses into distance. Ahead is a sky full of possibility — and probably a few mistakes."
]

def depart():
    return random.choice(DEPARTURE_TEXTS)
